### ISSUE TITLE
全体的にコマンド異常終了時の挙動が不安定

### ISSUE THREAD

**Issue by tmkw** [tmkw/sf_cli#255]
スクリプティングにおいては、コマンドが異常終了したことを検知して例外を出す必要がある。
このことが全体的に統一されてないので、確認の上、直していく必要がある。

**Comment by tmkw** [comment]
以下のコードで見る通り、jsonモードで実行している場合、処理結果を見て例外を出すようにしている。
```
 11         def exec(action, flags: {}, switches: {}, redirection: nil, raw_output: false, format: :json) # :doc:
 12           cmd = %|sf #{category} #{action}#{as_flag_options(flags)}#{as_switch_options(switches, format)}#{redirect redirection}|
 13 
 14           return `#{cmd}` if raw_output
 15 
 16           json = JSON.parse `#{cmd}`
 17           raise StandardError.new(json['message']) if json['status'] != 0
 18 
 19           json
 20         end
```

**Comment by tmkw** [comment]
raw_output がtrue ならコマンドの出力をそのままだし
リダイレクトの指定がなければ標準出力の内容はコンソールにそのまま表示される（スクリプティングではこれが余計なため、必要に応じてOFFとすることになる）

**Comment by tmkw** [comment]
## sf sobject describe
```
irb(main):001> sf.sobject.describe :Apatcha, target_org: :dev
/home/cul8er/projects/sf_cli/1.2.3/error_behavior/lib/sf_cli/sf/core/base.rb:17:in `exec': The requested resource does not exist (StandardError)
	from /home/cul8er/projects/sf_cli/1.2.3/error_behavior/lib/sf_cli/sf/sobject/describe.rb:27:in `describe'
	from (irb):1:in `<main>'
	from <internal:kernel>:187:in `loop'
	from /home/cul8er/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/irb-1.13.1/exe/irb:9:in `<top (required)>'
	from /home/cul8er/.rbenv/versions/3.3.4/bin/irb:25:in `load'
	from /home/cul8er/.rbenv/versions/3.3.4/bin/irb:25:in `<main>'
```

**Comment by tmkw** [comment]
当初はこれでも良いかと思っていたが、`alet` の実装も始まってみると、コマンドの実行エラーであることをこの例外の出し方では判断のしようがない。
コマンド実行失敗エラー例外を出すようにまず変える必要がある。

**Comment by tmkw** [comment]
done #260
